const { app, BrowserWindow, dialog, ipcMain, Menu } = require("electron");
const path = require("path");
const fs = require("fs/promises");
const os = require("os");
const { execFile } = require("child_process");



let mainWindow;
let agentConfig = {
  apiKey: "",
  apiUrl: "https://api.openai.com/v1/chat/completions",
  model: "gpt-4.1-mini",
};

function sanitizeName(name) {
  return String(name || "fluxide-project")
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, "-")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80) || "fluxide-project";
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 700,
    minWidth: 900,
    minHeight: 620,
    title: "FluxIDE",
    icon: path.join(__dirname, "icon.ico"),
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  Menu.setApplicationMenu(null);

  mainWindow.loadFile(path.join(__dirname, "frontend", "index.html"));
}

app.whenReady().then(createWindow);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

ipcMain.handle("agent:configure", (_event, config) => {
  agentConfig = {
    apiKey: String(config.apiKey || "").trim(),
    apiUrl: String(config.apiUrl || agentConfig.apiUrl).trim(),
    model: String(config.model || agentConfig.model).trim(),
  };
  return {
    ok: Boolean(agentConfig.apiKey && agentConfig.apiUrl && agentConfig.model),
    model: agentConfig.model,
    apiUrl: agentConfig.apiUrl,
  };
});

ipcMain.handle("dialog:chooseFolder", async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: "Choose FluxIDE Project Folder",
    properties: ["openDirectory", "createDirectory"],
  });
  if (result.canceled || !result.filePaths.length) return null;
  return result.filePaths[0];
});

ipcMain.handle("project:new", async (_event, payload) => {
  const baseFolder = payload.folder || path.join(os.homedir(), "Documents");
  const projectName = sanitizeName(payload.name || "fluxide-project");
  const projectFolder = path.join(baseFolder, projectName);
  await fs.mkdir(projectFolder, { recursive: true });
  const filePath = path.join(projectFolder, payload.fileName || "sketch.ino");
  await fs.writeFile(filePath, payload.code || "", "utf8");
  return { projectFolder, filePath };
});

ipcMain.handle("project:saveFile", async (_event, payload) => {
  const folder = payload.folder;
  if (!folder) throw new Error("Choose a project folder first.");
  await fs.mkdir(folder, { recursive: true });
  const filePath = path.join(folder, payload.fileName || "sketch.ino");
  await fs.writeFile(filePath, payload.code || "", "utf8");
  return { filePath };
});

ipcMain.handle("project:exportZip", async (_event, payload) => {
  const folder = payload.folder || path.join(os.homedir(), "Documents");
  await fs.mkdir(folder, { recursive: true });
  const zipPath = path.join(folder, `${sanitizeName(payload.name || "fluxide-project")}.zip`);
  const files = [
    { name: "sketch.ino", content: payload.code || "" },
    { name: "prompt.txt", content: payload.prompt || "" },
    { name: "project.txt", content: payload.subPrompt || "" },
    { name: "README.md", content: `# ${payload.name || "FluxIDE Project"}\n\nGenerated by FluxIDE.\n` },
  ];
  await fs.writeFile(zipPath, createZip(files));
  return { zipPath };
});

ipcMain.handle("board:upload", async (_event, payload) => {
  const code = String(payload.code || "").trim();
  const port = String(payload.port || "").trim();
  const board = String(payload.board || "Arduino Uno");
  const fqbn = boardToFqbn(board);

  if (!code) throw new Error("Generate or write code before uploading.");
  if (!port) throw new Error("Select a detected COM port before uploading.");
  if (!fqbn) throw new Error(`Upload is not mapped for ${board} yet.`);

  const sketchRoot = path.join(os.tmpdir(), "fluxide-upload");
  const sketchFolder = path.join(sketchRoot, "FluxIDESketch");
  const sketchPath = path.join(sketchFolder, "FluxIDESketch.ino");
  await fs.mkdir(sketchFolder, { recursive: true });
  await fs.writeFile(sketchPath, code, "utf8");

  try {
    await execFileAsync("arduino-cli", ["compile", "--fqbn", fqbn, sketchFolder]);
    const upload = await execFileAsync("arduino-cli", ["upload", "-p", port, "--fqbn", fqbn, sketchFolder]);
    return { ok: true, output: upload.stdout || upload.stderr || `Uploaded to ${port}` };
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error("arduino-cli is not installed or not in PATH. Install Arduino CLI, then try Upload again.");
    }
    throw new Error((error.stderr || error.stdout || error.message || "Upload failed").trim());
  }
});

ipcMain.handle("board:installLib", async (_event, libName) => {
  if (!libName) throw new Error("Library name required.");
  try {
    const install = await execFileAsync("arduino-cli", ["lib", "install", libName]);
    return { ok: true, output: install.stdout || install.stderr || `Installed ${libName}` };
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error("arduino-cli is not installed or not in PATH.");
    }
    throw new Error((error.stderr || error.stdout || error.message || "Install failed").trim());
  }
});

ipcMain.handle("board:installLibZip", async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    title: "Select Arduino Library .zip File",
    filters: [{ name: "ZIP Archives", extensions: ["zip"] }],
    properties: ["openFile"],
  });
  if (result.canceled || !result.filePaths.length) return { ok: false, message: "Cancelled" };
  const zipPath = result.filePaths[0];
  const libDir = getArduinoLibrariesDir();
  await fs.mkdir(libDir, { recursive: true });

  // Try arduino-cli first, fall back to PowerShell extraction
  try {
    const install = await execFileAsync("arduino-cli", ["lib", "install", "--zip-path", zipPath]);
    return { ok: true, output: install.stdout || install.stderr || `Installed from ${zipPath}` };
  } catch (cliErr) {
    // Fallback: extract zip manually via PowerShell
    try {
      await execPowerShell(`Expand-Archive -Path '${zipPath.replace(/'/g, "''")}' -DestinationPath '${libDir.replace(/'/g, "''")}' -Force`);
      const libName = path.basename(zipPath, ".zip");
      return { ok: true, output: `Extracted ${libName} to ${libDir}` };
    } catch (psErr) {
      throw new Error(`Failed to install zip library: ${(psErr.message || cliErr.message || "Unknown error").trim()}`);
    }
  }
});

ipcMain.handle("board:autoInstallLibs", async (_event, payload) => {
  const code = String(payload.code || "").trim();
  if (!code) throw new Error("No code provided to analyze.");

  // Parse #include <LibName.h> directives
  const includeRegex = /#include\s*[<"]([^>"]+)[>"]/g;
  const includes = [];
  let match;
  while ((match = includeRegex.exec(code)) !== null) {
    includes.push(match[1]);
  }

  if (!includes.length) return { ok: true, installed: [], skipped: [], message: "No #include directives found." };

  // Filter out standard Arduino/ESP built-in headers
  const builtins = new Set([
    "Arduino.h", "Wire.h", "SPI.h", "EEPROM.h", "Servo.h", "SoftwareSerial.h",
    "HardwareSerial.h", "WiFi.h", "WiFiClient.h", "WiFiServer.h", "WiFiUdp.h",
    "SD.h", "LiquidCrystal.h", "Ethernet.h", "EthernetClient.h", "EthernetServer.h",
    "Stepper.h", "Mouse.h", "Keyboard.h", "stdlib.h", "stdio.h", "string.h",
    "math.h", "avr/io.h", "avr/interrupt.h", "avr/pgmspace.h", "avr/wdt.h",
    "esp_wifi.h", "esp_system.h", "driver/gpio.h", "freertos/FreeRTOS.h",
  ]);

  const libNames = [];
  for (const inc of includes) {
    const base = inc.replace(/\.h$/i, "").trim();
    if (!builtins.has(inc) && base.length > 1) {
      libNames.push(base);
    }
  }

  if (!libNames.length) return { ok: true, installed: [], skipped: includes, message: "All includes are built-in libraries." };

  const installed = [];
  const failed = [];
  for (const lib of libNames) {
    try {
      await execFileAsync("arduino-cli", ["lib", "install", lib]);
      installed.push(lib);
    } catch {
      failed.push(lib);
    }
  }
  return { ok: true, installed, failed, message: `Installed ${installed.length}, failed ${failed.length}` };
});

ipcMain.handle("serial:list", async () => {
  if (process.platform !== "win32") return [];
  const script = [
    "$ports = Get-CimInstance Win32_PnPEntity |",
    "Where-Object { $_.Name -match '\\(COM\\d+\\)' } |",
    "ForEach-Object {",
    "  $port = [regex]::Match($_.Name, 'COM\\d+').Value;",
    "  [PSCustomObject]@{ port=$port; name=$_.Name; manufacturer=$_.Manufacturer; id=$_.PNPDeviceID }",
    "};",
    "$ports | ConvertTo-Json -Compress",
  ].join(" ");

  return new Promise((resolve) => {
    execFile("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", script], { windowsHide: true }, (error, stdout) => {
      if (error || !stdout.trim()) {
        resolve([]);
        return;
      }
      try {
        const parsed = JSON.parse(stdout);
        const ports = Array.isArray(parsed) ? parsed : [parsed];
        resolve(ports
          .filter((item) => item && item.port)
          .map((item) => ({
            port: item.port,
            name: item.name || item.port,
            manufacturer: item.manufacturer || "Unknown",
            id: item.id || "",
          })));
      } catch {
        resolve([]);
      }
    });
  });
});

ipcMain.handle("agent:generate", async (event, payload) => {
  if (!agentConfig.apiKey || !agentConfig.model || !agentConfig.apiUrl) {
    throw new Error("Open Agent settings and confirm your API key, API URL, and model first.");
  }

  const prompt = String(payload.prompt || "").trim();
  const subPrompt = String(payload.subPrompt || "").trim();
  const board = String(payload.board || "Arduino Uno");
  const port = String(payload.port || "No COM port selected");
  const lang = String(payload.lang || "C++ (Arduino)");
  let apiUrl = agentConfig.apiUrl.replace(/\/+$/, "");
  const isAnthropic = /anthropic\.com/i.test(apiUrl);
  if (!isAnthropic && !apiUrl.endsWith("/chat/completions")) {
    if (!apiUrl.endsWith("/v1")) apiUrl += "/v1";
    apiUrl += "/chat/completions";
  }

  const system = [
    "You are FluxIDE, an expert embedded systems and app coding agent.",
    `Target board: ${board}.`,
    `Selected serial port: ${port}.`,
    `Language/runtime: ${lang}.`,
    "Write complete, valid, and compilable C++ code only. Include concise comments where useful.",
    "CRITICAL ARDUINO RULES:",
    "1. NEVER output placeholders like @@STR0@@. You MUST use real C++ strings in quotes (e.g. \"Hello\").",
    "2. ONLY use standard Arduino core functions (digitalWrite, pinMode, etc.). Do NOT invent fake functions like digitalWriteToLed.",
    "3. There must be exactly ONE void setup() and ONE void loop(). NEVER create duplicate setup functions.",
    "4. NEVER leave void loop() empty! If the task is a static one-time message, you MUST add a heartbeat blink (e.g. blinking LED_BUILTIN) or a delay loop.",
    "End with a line starting exactly // EXPLAIN: followed by a short explanation.",
    "If hardware components are involved, also add a line starting exactly // PINOUT: followed by a simple list of pin connections (e.g., Arduino GND - Ultrasonic GND).",
  ].join("\n");
  const user = [
    subPrompt ? `Project definition:\n${subPrompt}` : "",
    `Build request:\n${prompt}`,
    "Return code as plain text. Do not use markdown fences.",
  ].filter(Boolean).join("\n\n");

  const response = await fetch(apiUrl, {
    method: "POST",
    headers: isAnthropic
      ? {
        "content-type": "application/json",
        "x-api-key": agentConfig.apiKey,
        "anthropic-version": "2023-06-01",
      }
      : {
        "content-type": "application/json",
        "authorization": `Bearer ${agentConfig.apiKey}`,
      },
    body: JSON.stringify(isAnthropic
      ? {
        model: agentConfig.model,
        max_tokens: 8000,
        system,
        stream: true,
        messages: [{ role: "user", content: user }],
      }
      : {
        model: agentConfig.model,
        max_tokens: 8000,
        stream: true,
        stream_options: { include_usage: true },
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
      }),
  });

  if (!response.ok || !response.body) {
    const text = await response.text().catch(() => "");
    throw new Error(`Agent request failed (${response.status}): ${text.slice(0, 240)}`);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let fullText = "";

  function emit(text) {
    if (!text) return;
    fullText += text;
    event.sender.send("agent:chunk", text);
  }

  let totalTokens = 0;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop() || "";
    for (const line of lines) {
      if (!line.startsWith("data:")) continue;
      const data = line.slice(5).trim();
      if (!data || data === "[DONE]") continue;
      try {
        const json = JSON.parse(data);
        if (json.usage && json.usage.total_tokens) {
          totalTokens = json.usage.total_tokens;
        } else if (json.message && json.message.usage) {
          totalTokens = json.message.usage.input_tokens + json.message.usage.output_tokens;
        }

        emit(isAnthropic
          ? json.delta?.text
          : json.choices?.[0]?.delta?.content);
      } catch {
        // Ignore keepalive or provider-specific stream metadata.
      }
    }
  }

  // Fallback heuristic if API doesn't return usage
  if (!totalTokens) {
    totalTokens = Math.ceil((prompt.length + subPrompt.length + fullText.length) / 3.5);
  }

  event.sender.send("agent:done", { text: fullText, tokens: totalTokens });
  return { text: fullText, tokens: totalTokens };
});

function createZip(files) {
  const localParts = [];
  const centralParts = [];
  let offset = 0;

  for (const file of files) {
    const name = Buffer.from(file.name.replace(/\\/g, "/"));
    const content = Buffer.from(file.content || "", "utf8");
    const crc = crc32(content);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0, 6);
    local.writeUInt16LE(0, 8);
    local.writeUInt16LE(0, 10);
    local.writeUInt16LE(0, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(content.length, 18);
    local.writeUInt32LE(content.length, 22);
    local.writeUInt16LE(name.length, 26);
    local.writeUInt16LE(0, 28);
    localParts.push(local, name, content);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0, 8);
    central.writeUInt16LE(0, 10);
    central.writeUInt16LE(0, 12);
    central.writeUInt16LE(0, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(content.length, 20);
    central.writeUInt32LE(content.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt16LE(0, 30);
    central.writeUInt16LE(0, 32);
    central.writeUInt16LE(0, 34);
    central.writeUInt16LE(0, 36);
    central.writeUInt32LE(0, 38);
    central.writeUInt32LE(offset, 42);
    centralParts.push(central, name);
    offset += local.length + name.length + content.length;
  }

  const centralSize = centralParts.reduce((sum, part) => sum + part.length, 0);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(files.length, 8);
  end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(centralSize, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20);
  return Buffer.concat([...localParts, ...centralParts, end]);
}

function crc32(buffer) {
  let crc = -1;
  for (const byte of buffer) {
    crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ byte) & 0xff];
  }
  return (crc ^ -1) >>> 0;
}

const CRC_TABLE = Array.from({ length: 256 }, (_v, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function boardToFqbn(board) {
  const value = String(board || "").toLowerCase();
  if (value.includes("uno")) return "arduino:avr:uno";
  if (value.includes("mega")) return "arduino:avr:mega";
  if (value.includes("nano")) return "arduino:avr:nano";
  if (value.includes("leonardo")) return "arduino:avr:leonardo";
  if (value.includes("micro")) return "arduino:avr:micro";
  if (value.includes("due")) return "arduino:sam:arduino_due_x";
  if (value.includes("esp32")) return "esp32:esp32:esp32";
  if (value.includes("esp8266")) return "esp8266:esp8266:nodemcuv2";
  return "";
}

function execFileAsync(command, args) {
  return new Promise((resolve, reject) => {
    const options = { windowsHide: true, timeout: 120000, env: { ...process.env } };
    if (process.platform === 'win32') {
      const cliDir = path.join(process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local'), 'Programs', 'arduino-cli');
      options.env.PATH = options.env.PATH ? `${options.env.PATH};${cliDir}` : cliDir;
    }
    execFile(command, args, options, (error, stdout, stderr) => {
      if (error) {
        error.stdout = stdout;
        error.stderr = stderr;
        reject(error);
      } else {
        resolve({ stdout, stderr });
      }
    });
  });
}

ipcMain.handle("sys:terminal", async (_event, cmd) => {
  try {
    const { stdout, stderr } = await execPowerShell(cmd);
    return { ok: true, output: stdout || stderr || "Success (no output)" };
  } catch (error) {
    return { ok: false, output: error.stdout || error.stderr || error.message || "Unknown error" };
  }
});

function getArduinoLibrariesDir() {
  if (process.platform === "win32") {
    return path.join(os.homedir(), "Documents", "Arduino", "libraries");
  }
  return path.join(os.homedir(), "Arduino", "libraries");
}

function execPowerShell(command) {
  return new Promise((resolve, reject) => {
    execFile("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", command], { windowsHide: true, timeout: 60000 }, (error, stdout, stderr) => {
      if (error) {
        error.stdout = stdout;
        error.stderr = stderr;
        reject(error);
      } else {
        resolve({ stdout, stderr });
      }
    });
  });
}
